### PR TITLE
Layout/UI Improvements 2

### PR DESCRIPTION
**Pull request by darrylyeo**
- Fix button border
- Cleaner padding on `.scratchpad-toolbar`

### CODE REVIEW

**Comment by codeHusky** [comment]
Your previous changes have essentially broke building of the live-editor for me. I'm not sure how your builds work while mine don't.

**Comment by codeHusky** [comment]
I'm getting the `this.merge` error now.

**Comment by codeHusky** [comment]
Manually merged changes.

**Comment by darrylyeo** [comment]
Huh, how strange.

**Pull request closed without merging**
