### PR TITLE
Layout/UI Improvements

### PR DESCRIPTION
**Pull request by darrylyeo**
- Fixed arrow on color picker
- Mobile responsive layout
- Cleaner borders
- Oh Noes animations
- Drastically refactored HTML and CSS (especially Oh Noes popup)

### CODE REVIEW

**Comment by codeHusky** [comment]
image
Doesn't work on small/default canvas sizes

**Comment by codeHusky** [comment]
image

**Comment by codeHusky** [comment]
image
To solve the issue, all that needs to be done is fix the word wrap / word break on the text.

**Comment by codeHusky** [comment]
image
With a height of 800px

**Comment by darrylyeo** [comment]
How did you get it to misalign like that? Variable height is working for me in the demos.

**Comment by codeHusky** [comment]
image
First issue is fixed

**Comment by codeHusky** [comment]
http://localhost:8000/demos/simple/?height=800

**Comment by codeHusky** [comment]
Opening the dev menu / resizing the viewport seems to convince it to snap back into size

**Comment by codeHusky** [comment]
image
Editor resizing is broken now.

**Comment by darrylyeo** [comment]
Resizing should work again. Can't seem to replicate the misalignment.

**Comment by darrylyeo** [comment]
The number scrubber being off is due to Bootstrap loading after the Live Editor CSS instead of before.

**Comment by codeHusky** [comment]
I'll sort out the rest of the issues myself. :)

**Pull request merged**
